logging:
  level:
    com:
      gc:
        inmemorydb: debug
spring:
# ========================= 测试环境使用以下配置，master 和 tt 均配置为oracle
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      datasource:
#        master:
#          url: jdbc:oracle:thin:@192.168.1.15:1521:xe
#          username: memory
#          password: memory
#          driver-class-name: oracle.jdbc.driver.OracleDriver
#          hikari:
#            max-lifetime: 1765000
#            maximum-pool-size: 15
#        tt:
#          url: jdbc:oracle:thin:@192.168.1.15:1521:xe
#          username: memory
#          password: memory
#          driver-class-name: oracle.jdbc.driver.OracleDriver
#          hikari:
#            max-lifetime: 1765000
#            maximum-pool-size: 15
# ========================= 安装有 tt client 的环境使用以下配置，master 配置为oracle，tt 配置为 tt
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:oracle:thin:@192.168.1.15:1521:xe
          username: memory
          password: memory
          driver-class-name: oracle.jdbc.driver.OracleDriver
          hikari:
            max-lifetime: 1765000
            maximum-pool-size: 15
        tt:
          url: jdbc:timesten:client:dsn=tt1122;uid=memory;pwd=memory
          username: memory
          password: memory
          driver-class-name: com.timesten.jdbc.TimesTenDriver
          hikari:
            max-lifetime: 1765000
            maximum-pool-size: 15
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 10000
    pool:
      max-active: 10
      min-idle: 3
      max-idle: 5
  aop:
    proxy-target-class: true
    auto: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 8484